import {
  GraduationCap,
  Menu,
  X,
  Twitter,
  Github,
  Search,
  User,
  Moon,
  Sun,
  Laptop,
  Award,
  Clock,
  Globe,
  Play,
  BookOpen,
  FileText,
  CheckCircle,
  CreditCard,
  Linkedin,
  LayoutGrid,
  List,
  Loader2,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Users,
  Facebook,
  Instagram,
  Youtube,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ExternalLink,
  Camera,
  Star,
  Settings,
  LogOut,
  Zap,
  Shield,
  Chrome,
  Apple,
  Trophy,
  Lightbulb,
  Handshake,
  UsersRound,
  Globe2,
  CalendarClock,
  FileBadge,
  UserCheck,
  Sparkles,
  Rocket,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: GraduationCap,
  menu: Menu,
  close: X,
  twitter: Twitter,
  gitHub: Github,
  linkedin: Linkedin,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  search: Search,
  user: User,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  award: Award,
  clock: Clock,
  globe: Globe,
  play: Play,
  book: BookOpen,
  fileText: FileText,
  check: CheckCircle,
  creditCard: CreditCard,
  grid: LayoutGrid,
  list: List,
  spinner: Loader2,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  users: Users,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  externalLink: ExternalLink,
  camera: Camera,
  star: Star,
  settings: Settings,
  logout: LogOut,
  zap: Zap,
  shield: Shield,
  google: Chrome,
  apple: Apple,
  // Enhanced Icons
  trophy: Trophy,
  lightbulb: Lightbulb,
  handshake: Handshake,
  usersRound: UsersRound,
  globe2: Globe2,
  calendarClock: CalendarClock,
  fileBadge: FileBadge,
  userCheck: UserCheck,
  sparkles: Sparkles,
  rocket: Rocket,
};
