// Find-or-insert helper for AI-generated recipes. Without this, every
// "Regenerate this week's meals" click creates 21 new rows even when the
// model produces the same recipe names — the recipes table grows
// without bound. With it, repeat generations reuse rows and the table
// stays compact.
//
// Match key: (owner_id, name, kcal, protein) + the "auto-generated" tag.
// We don't dedup user-created recipes — only the bulk planner output.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { GeneratedRecipe } from "@/lib/ai/prompts/recipe";
import { maybeRefineRecipe } from "@/lib/nutrition/recipe-macros";

// Dedup lookup for auto-generated recipes. Single source of truth for
// the match criteria — used both as a pre-insert dedupe check AND as
// the post-INSERT lookup when the partial unique index catches a
// cross-request race (migration 0021). Keeping these inline at both
// call sites was inviting drift if the dedup key ever changes.
async function findExistingAutoGeneratedRecipeId(
  supabase: SupabaseClient,
  userId: string,
  recipe: { name: string; kcal: number; protein: number },
): Promise<string | null> {
  const { data } = await supabase
    .from("recipes")
    .select("id")
    .eq("owner_id", userId)
    .eq("name", recipe.name)
    .eq("kcal", recipe.kcal)
    .eq("protein", recipe.protein)
    .contains("tags", ["auto-generated"])
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();
  return (data?.id as string | undefined) ?? null;
}

export async function upsertAutoGeneratedRecipe(args: {
  supabase: SupabaseClient;
  userId: string;
  recipe: GeneratedRecipe;
  photoUrl: string | null;
  defaultServings: number;
}): Promise<string | null> {
  const { supabase, userId, defaultServings } = args;
  // Defensive guard: never persist a data: URI to recipes.photo_url.
  // resolveRecipePhoto's AI-gen fallback used to return data URIs, which
  // produced ~1.3 MB strings inlined into every HTML page referencing
  // that recipe — a 21-meal plan could lock the browser. The resolver
  // now uploads to Storage, but a regression here would silently break
  // production again, so we drop the URL rather than risk it.
  const photoUrl =
    args.photoUrl && args.photoUrl.startsWith("data:")
      ? (console.warn(
          `upsertAutoGeneratedRecipe: dropped data: photo_url for "${args.recipe.name}" (would lock the browser)`,
        ),
        null)
      : args.photoUrl;
  // Refine AI macros against USDA FDC when configured. The dedup key
  // includes kcal + protein, so refining here means a recipe whose AI
  // estimate "happens to match" a previous run won't accidentally dedup
  // against an unrefined row — refined macros land in the dedup key
  // consistently because we always refine before lookup.
  const recipe = await maybeRefineRecipe(args.recipe);

  // Look for an existing auto-generated recipe with the same name + macros
  // for this user. Using kcal + protein as the secondary signal catches
  // intentional remixes (different macros = different recipe).
  const existingId = await findExistingAutoGeneratedRecipeId(
    supabase,
    userId,
    recipe,
  );
  if (existingId) return existingId;

  const { data: inserted, error } = await supabase
    .from("recipes")
    .insert({
      owner_id: userId,
      name: recipe.name,
      photo_url: photoUrl,
      source_url: null,
      ingredients_json: recipe.ingredients,
      steps_json: recipe.steps,
      kcal: recipe.kcal,
      protein: recipe.protein,
      carbs: recipe.carbs,
      fat: recipe.fat,
      time_min: recipe.time_min,
      servings: recipe.servings ?? defaultServings,
      family_notes_json: recipe.family_modifications ?? [],
      tips_json: recipe.tips ?? [],
      tags: [...new Set([...(recipe.tags ?? []), "auto-generated"])],
    })
    .select("id")
    .single();

  if (error) {
    // 23505 = unique_violation. The partial unique index added in
    // migration 0021 (recipes_auto_generated_unique_idx) catches the
    // cross-request race where two concurrent saves both miss the
    // SELECT above and both try to INSERT. The loser of the race
    // re-selects to find the winner's row and returns its id, so the
    // caller's leftover refs still resolve correctly.
    if ((error as { code?: string }).code === "23505") {
      return findExistingAutoGeneratedRecipeId(supabase, userId, recipe);
    }
    return null;
  }
  if (!inserted) return null;
  return inserted.id as string;
}
