import type { Metadata } from "next";
import 'swiper/css';
import 'swiper/css/navigation';
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import AOSInitializer from "@/components/aos/AOSInitializer";
import { Open_Sans } from "next/font/google";
const geistOpenSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistOpenSans.variable}  antialiased`}
      >
        <AOSInitializer />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
