repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bun run lint
        language: system
        files: \.[jt]sx?$
        pass_filenames: false
      - id: format
        name: format
        entry: bun run format
        language: system
        files: \.(js|jsx|ts|tsx|json|md|css)$
      - id: typecheck
        name: typecheck
        entry: bun run typecheck
        language: system
        always_run: true
        pass_filenames: false
