-- ══════════════════════════════════════════════════════
-- Migration 006: App Improvements v2
-- item_categories, family_members, school_tests,
-- projects.assignee column
-- ══════════════════════════════════════════════════════

-- 1. item_categories — persistent item-to-category mapping
CREATE TABLE IF NOT EXISTS item_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,          -- stored lowercase
  category text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE item_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Family access" ON item_categories
  FOR ALL USING (is_allowed_user())
  WITH CHECK (is_allowed_user());

-- 2. family_members — email-to-name+role mapping
CREATE TABLE IF NOT EXISTS family_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text UNIQUE NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('parent', 'kid')),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Family access" ON family_members
  FOR ALL USING (is_allowed_user())
  WITH CHECK (is_allowed_user());

-- Seed family members (replace with your family's details)
INSERT INTO family_members (email, name, role) VALUES
  ('parent1@gmail.com', 'Parent1', 'parent'),
  ('parent2@gmail.com', 'Parent2', 'parent'),
  ('kid1@gmail.com', 'Kid1', 'kid'),
  ('kid2@gmail.com', 'Kid2', 'kid'),
  ('kid3@gmail.com', 'Kid3', 'kid')
ON CONFLICT (email) DO NOTHING;

-- 3. school_tests table
CREATE TABLE IF NOT EXISTS school_tests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kid_name text NOT NULL,
  subject text NOT NULL,
  test_date date NOT NULL,
  notes text,
  grade text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE school_tests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Family access" ON school_tests
  FOR ALL USING (is_allowed_user())
  WITH CHECK (is_allowed_user());

-- 4. Add assignee column to projects
ALTER TABLE projects ADD COLUMN IF NOT EXISTS assignee text;
