import { NextResponse, type NextRequest } from "next/server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { resolveRecipePhoto } from "@/lib/ai/photo";
import { PlanWeekSchema, type PlanSlot } from "@/lib/ai/prompts/plan-week";
import { upsertAutoGeneratedRecipe } from "@/lib/recipes/upsert-auto-generated";
import type { FamilyMember } from "@/lib/family";

// Saves the AI's already-streamed plan: resolves photos in parallel,
// writes recipes + plan_entries (with leftover propagation). Mirrors the
// shape of the legacy /api/ai/plan-week route's save phase, just driven
// by a client-supplied result instead of a server-side AI call.

// Photo resolution + 21 inserts can take longer than the previous 120s
// budget when the photo chain has to go all the way through Brave/Pexels
// for every meal. 300s = Vercel default, plenty of headroom.
export const maxDuration = 300;

const REQUIRED_SLOTS: PlanSlot[] = ["breakfast", "lunch", "dinner"];

function startOfWeek(d: Date): Date {
  const day = d.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  const out = new Date(d);
  out.setDate(d.getDate() + diff);
  out.setHours(0, 0, 0, 0);
  return out;
}

function isValidDate(s: string): boolean {
  return /^\d{4}-\d{2}-\d{2}$/.test(s) && !Number.isNaN(Date.parse(s));
}

const Body = z.object({
  week_start: z.string().optional(),
  include_snack: z.boolean().optional(),
  include_dessert: z.boolean().optional(),
  include_beverage: z.boolean().optional(),
  regenerate: z.boolean().optional(),
  result: PlanWeekSchema,
});

export async function POST(req: NextRequest) {
  try {
    const json = await req.json().catch(() => null);
    const parsed = Body.safeParse(json);
    if (!parsed.success) {
      return NextResponse.json(
        { error: `Invalid body: ${parsed.error.message}` },
        { status: 400 },
      );
    }
    const body = parsed.data;

    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { data: profile } = await supabase
      .from("profiles")
      .select("family_json")
      .eq("id", user.id)
      .maybeSingle();
    const family = (
      (profile as { family_json?: FamilyMember[] | null } | null)?.family_json ??
      []
    ).filter((f) => f.name && f.name.trim().length > 0);

    const slots: PlanSlot[] = [...REQUIRED_SLOTS];
    if (body.include_snack) slots.push("snack");
    if (body.include_dessert) slots.push("dessert");
    if (body.include_beverage) slots.push("beverage");

    const requestedWeek =
      body.week_start && isValidDate(body.week_start)
        ? new Date(`${body.week_start}T00:00:00`)
        : new Date();
    const start = startOfWeek(requestedWeek);
    const dates = Array.from({ length: 7 }, (_, i) => {
      const d = new Date(start);
      d.setDate(start.getDate() + i);
      return d.toISOString().slice(0, 10);
    });

    // Optional regenerate: drop existing planned entries for this week +
    // these slots before insert. Logged/skipped never touched.
    if (body.regenerate) {
      await supabase
        .from("meal_plan_entries")
        .delete()
        .eq("user_id", user.id)
        .eq("status", "planned")
        .gte("date", dates[0])
        .lte("date", dates[6])
        .in("slot", slots);
    }

    const { data: existingPlans } = await supabase
      .from("meal_plan_entries")
      .select("date, slot")
      .eq("user_id", user.id)
      .gte("date", dates[0])
      .lte("date", dates[6])
      .in("slot", slots);
    const filledKeys = new Set(
      (existingPlans ?? []).map((e) => `${e.date}|${e.slot}`),
    );

    const meals = body.result.meals;

    // Resolve photos up-front in parallel for meals with a recipe AND
    // not already-filled. AI-supplied image URLs win in the resolver.
    const photoTargets: Array<{
      index: number;
      recipeName: string;
      aiImageUrl: string | null;
      promptHint: string;
    }> = [];
    meals.forEach((m, i) => {
      const slotOk = slots.includes(m.slot as PlanSlot);
      const dateOk = dates.includes(m.date);
      const filled = filledKeys.has(`${m.date}|${m.slot}`);
      if (m.recipe && slotOk && dateOk && !filled) {
        photoTargets.push({
          index: i,
          recipeName: m.recipe.name,
          aiImageUrl: m.recipe.image_url ?? null,
          promptHint: m.recipe.tags?.slice(0, 3).join(", ") ?? "",
        });
      }
    });
    const resolvedPhotos = await Promise.all(
      photoTargets.map((t) =>
        resolveRecipePhoto({
          recipeName: t.recipeName,
          aiImageUrl: t.aiImageUrl,
          promptHint: t.promptHint,
          supabase,
          userId: user.id,
        }).catch(() => null),
      ),
    );
    const photoByIndex = new Map<number, string | null>();
    photoTargets.forEach((t, j) => {
      photoByIndex.set(t.index, resolvedPhotos[j]?.url ?? null);
    });

    const created: Array<{ date: string; slot: string; recipe_name: string }> = [];
    const skipped = filledKeys.size;
    const entryIdByIndex = new Map<number, string>();
    const recipeIdByIndex = new Map<number, string>();

    // Filter to actionable meals (within target dates/slots, not already
    // filled). Split into "fresh" and "leftover" so Phase A inserts can
    // all run in parallel before Phase B (leftovers) consumes their IDs.
    // This used to be a single sequential for-loop awaiting ~3 DB
    // roundtrips per meal × 21 meals ≈ 3-5s of avoidable latency, which
    // showed up in production as a long "Saving + finding photos…" hang
    // and gave users time to impatiently re-click Generate (compounding
    // the problem).
    const actionable = meals
      .map((m, i) => ({ m, i }))
      .filter(
        ({ m }) =>
          dates.includes(m.date) &&
          slots.includes(m.slot as PlanSlot) &&
          !filledKeys.has(`${m.date}|${m.slot}`),
      );
    const freshTargets = actionable.filter(
      ({ m }) => m.recipe && typeof m.is_leftover_of_index !== "number",
    );
    const leftoverTargets = actionable.filter(
      ({ m }) => typeof m.is_leftover_of_index === "number",
    );

    // Phase A — fresh recipes, fully parallel. Each task does the recipe
    // upsert and the plan-entry upsert for one meal index. The upserts
    // are idempotent (ignoreDuplicates on the user_id,date,slot unique
    // constraint added in migration 0016) so concurrent save calls
    // converge instead of stacking duplicate rows.
    //
    // Within-request dedupe: upsertAutoGeneratedRecipe does a SELECT-
    // then-INSERT against (owner_id, name, kcal, protein, tags). If two
    // meals in the same plan share that signature (e.g. dinner Monday
    // and lunch Friday both "Sheet pan chicken thighs"), running both
    // in parallel races: both SELECTs miss, both INSERTs win, dupe row
    // created. Map<key, Promise<id>> coalesces parallel calls for the
    // same recipe to a single upsert. (Cross-request races are still
    // possible; mitigated separately by the unique constraint added
    // in migration 0016 for plan_entries and the post-hoc dedup script
    // we ran for recipes — a DB-level partial unique index on recipes
    // would be the durable fix, deferred to a follow-up migration.)
    const recipeUpsertCache = new Map<string, Promise<string | null>>();
    const recipeKey = (r: { name: string; kcal: number; protein: number }) =>
      `${r.name.trim().toLowerCase()}|${r.kcal}|${r.protein}`;
    const freshResults = await Promise.all(
      freshTargets.map(async ({ m, i }) => {
        const r = m.recipe;
        if (!r) return null;
        const key = recipeKey(r);
        let recipePromise = recipeUpsertCache.get(key);
        if (!recipePromise) {
          recipePromise = upsertAutoGeneratedRecipe({
            supabase,
            userId: user.id,
            recipe: r,
            photoUrl: photoByIndex.get(i) ?? null,
            defaultServings: 1 + family.length,
          });
          recipeUpsertCache.set(key, recipePromise);
        }
        const recipeId = await recipePromise;
        if (!recipeId) return null;

        const { data: upsertedRow } = await supabase
          .from("meal_plan_entries")
          .upsert(
            {
              user_id: user.id,
              date: m.date,
              slot: m.slot,
              recipe_id: recipeId,
              status: "planned",
            },
            { onConflict: "user_id,date,slot", ignoreDuplicates: true },
          )
          .select("id")
          .maybeSingle();

        let entryId = upsertedRow?.id as string | undefined;
        // Inheritance from the conflicting row: if the slot was already
        // filled (e.g. by a concurrent save), our recipe_id is rejected
        // and the existing recipe_id stands. Leftover entries in Phase B
        // must reference the EXISTING recipe, not the one we tried to
        // insert, or they'll point at a row that isn't actually planned
        // for that slot.
        let effectiveRecipeId = recipeId;
        if (!entryId) {
          const { data: existing } = await supabase
            .from("meal_plan_entries")
            .select("id, recipe_id")
            .eq("user_id", user.id)
            .eq("date", m.date)
            .eq("slot", m.slot)
            .maybeSingle();
          entryId = existing?.id as string | undefined;
          if (existing?.recipe_id) {
            effectiveRecipeId = existing.recipe_id as string;
          }
        }

        return {
          i,
          recipeId: effectiveRecipeId,
          entryId,
          date: m.date,
          slot: m.slot,
          recipe_name: r.name,
        };
      }),
    );
    for (const r of freshResults) {
      if (!r) continue;
      recipeIdByIndex.set(r.i, r.recipeId);
      if (r.entryId) entryIdByIndex.set(r.i, r.entryId);
      created.push({ date: r.date, slot: r.slot, recipe_name: r.recipe_name });
    }

    // Phase B — leftover entries, parallel. All Phase A inserts have
    // landed by now so source refs are resolvable.
    const leftoverResults = await Promise.all(
      leftoverTargets.map(async ({ m, i }) => {
        const sourceIdx = m.is_leftover_of_index as number;
        if (sourceIdx >= i) return null;
        const sourceEntryId = entryIdByIndex.get(sourceIdx);
        const sourceRecipeId = recipeIdByIndex.get(sourceIdx);
        if (!sourceEntryId || !sourceRecipeId) return null;

        await supabase.from("meal_plan_entries").upsert(
          {
            user_id: user.id,
            date: m.date,
            slot: m.slot,
            recipe_id: sourceRecipeId,
            status: "planned",
            is_leftover_of: sourceEntryId,
          },
          { onConflict: "user_id,date,slot", ignoreDuplicates: true },
        );
        return {
          date: m.date,
          slot: m.slot,
          recipe_name: `(leftover) ${meals[sourceIdx]?.recipe?.name ?? "earlier meal"}`,
        };
      }),
    );
    for (const r of leftoverResults) {
      if (r) created.push(r);
    }

    revalidatePath("/plan");
    revalidatePath("/today");
    revalidatePath("/recipes");
    revalidatePath("/shop");

    return NextResponse.json({ ok: true, created, skipped });
  } catch (err) {
    return NextResponse.json(
      { error: `Server error: ${(err as Error).message ?? "unknown"}` },
      { status: 500 },
    );
  }
}
