/**
 * Smart Matching engine — computes a 0-100 match score between the current
 * user and every other active user, using a 5-signal weighted formula.
 *
 *   Skill     × 25
 *   Industry  × 15
 *   Intent    × 30   (complementary — hiring <-> looking-for-work, etc.)
 *   Behavior  × 20   (overlap in liked post authors + mutual follows)
 *   Network   × 10   (mutual accepted connections)
 *
 * Output: top N candidates with reasons[] explaining WHY they matched.
 *
 * Candidates scoring ≥ 60 are post-processed with an Anthropic-generated
 * natural-language reason (see ./ai.ts). The heuristic reasons are always
 * produced first so we can fall back silently if the AI path fails.
 */

import { generateMatchReason, type UserContext } from "./ai";

// Intentionally loose — the server and client create-functions in this
// codebase expose slightly different generic parameters, so we take the
// lowest common denominator here instead of fighting the type system.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SupabaseClient = any;

// ---------- types ----------

export type MatchCandidate = {
  user_id: string;
  username: string;
  full_name: string | null;
  avatar_url: string | null;
  bio: string | null;

  score: number;                  // 0-100 rounded
  label: "perfect" | "strong" | "good" | "explore";
  reasons: string[];              // e.g. "Same industry: EdTech"

  // Natural-language reason generated by Claude (present when score >= 60
  // and ANTHROPIC_API_KEY is configured). When present, UI should prefer
  // this over the heuristic `reasons[0]`.
  ai_reason?: string | null;

  // connection state vs the caller
  connection_status: "none" | "pending_outgoing" | "pending_incoming" | "connected";

  // breakdown for debugging / UI
  breakdown: {
    skill: number;
    industry: number;
    intent: number;
    behavior: number;
    network: number;
  };
};

export type UserSignals = {
  user_id: string;
  skills: Set<string>;
  tools: Set<string>;
  industries: Set<string>;     // may have multiple if inferred from PoW posts
  intent: string | null;
  looking_for: Set<string>;
  liked_authors: Set<string>;  // whose posts they've liked
  follows: Set<string>;        // who they follow
  connections: Set<string>;    // accepted peer ids
};

// ---------- label from score ----------

export function labelFor(score: number): MatchCandidate["label"] {
  if (score >= 90) return "perfect";
  if (score >= 75) return "strong";
  if (score >= 60) return "good";
  return "explore";
}

// ---------- signal builders ----------

export async function buildUserSignals(
  supabase: SupabaseClient,
  userId: string,
): Promise<UserSignals> {
  const [
    prefsRes,
    powRes,
    likesRes,
    followsRes,
    connsRes,
  ] = await Promise.all([
    supabase
      .from("user_matching_prefs")
      .select("industry, intent, looking_for")
      .eq("user_id", userId)
      .maybeSingle(),
    supabase
      .from("proof_of_work_meta")
      .select("skills, tools, industry, intent, post_id, posts!inner(user_id)")
      .eq("posts.user_id", userId),
    supabase
      .from("likes")
      .select("post_id, posts!inner(user_id)")
      .eq("user_id", userId)
      .limit(500),
    supabase
      .from("follows")
      .select("following_id")
      .eq("follower_id", userId)
      .limit(500),
    supabase
      .from("my_network")
      .select("peer_id")
      .eq("user_id", userId),
  ]);

  const skills = new Set<string>();
  const tools = new Set<string>();
  const industries = new Set<string>();

  type PowRow = {
    skills?: string[] | null;
    tools?: string[] | null;
    industry?: string | null;
    intent?: string | null;
  };
  for (const row of ((powRes.data as PowRow[] | null) ?? [])) {
    for (const s of row.skills ?? []) skills.add(s.toLowerCase());
    for (const t of row.tools ?? []) tools.add(t.toLowerCase());
    if (row.industry) industries.add(row.industry.toLowerCase());
  }

  // Prefs industry overrides / augments PoW industries
  const prefs = prefsRes.data as
    | { industry?: string | null; intent?: string | null; looking_for?: string[] | null }
    | null;
  if (prefs?.industry) industries.add(prefs.industry.toLowerCase());

  const liked_authors = new Set<string>();
  type LikeRow = { posts?: { user_id: string } | { user_id: string }[] | null };
  for (const row of ((likesRes.data as LikeRow[] | null) ?? [])) {
    const p = Array.isArray(row.posts) ? row.posts[0] : row.posts;
    if (p?.user_id) liked_authors.add(p.user_id);
  }

  const follows = new Set<string>();
  for (const row of ((followsRes.data as { following_id: string }[] | null) ?? [])) {
    follows.add(row.following_id);
  }

  const connections = new Set<string>();
  for (const row of ((connsRes.data as { peer_id: string }[] | null) ?? [])) {
    connections.add(row.peer_id);
  }

  return {
    user_id: userId,
    skills,
    tools,
    industries,
    intent: prefs?.intent ?? null,
    looking_for: new Set((prefs?.looking_for ?? []).map((s) => s.toLowerCase())),
    liked_authors,
    follows,
    connections,
  };
}

// ---------- individual signal scorers (return 0..1) ----------

/** Jaccard similarity; also boosted slightly by absolute overlap size. */
function jaccard(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 || b.size === 0) return 0;
  let inter = 0;
  for (const x of a) if (b.has(x)) inter++;
  const union = a.size + b.size - inter;
  return union === 0 ? 0 : inter / union;
}

function overlap(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 || b.size === 0) return 0;
  let n = 0;
  for (const x of a) if (b.has(x)) n++;
  return n;
}

function skillScore(me: UserSignals, them: UserSignals): {
  v: number;
  reason: string | null;
} {
  const all_me = new Set([...me.skills, ...me.tools]);
  const all_them = new Set([...them.skills, ...them.tools]);
  const v = jaccard(all_me, all_them);
  if (v === 0) return { v: 0, reason: null };
  // Find the top shared skill to use in the reason
  const shared: string[] = [];
  for (const x of all_me) if (all_them.has(x)) shared.push(x);
  const top = shared.slice(0, 3).join(", ");
  return {
    v,
    reason: top ? `Shared stack: ${top}` : null,
  };
}

function industryScore(me: UserSignals, them: UserSignals): {
  v: number;
  reason: string | null;
} {
  if (me.industries.size === 0 || them.industries.size === 0) {
    return { v: 0, reason: null };
  }
  const shared: string[] = [];
  for (const x of me.industries) if (them.industries.has(x)) shared.push(x);
  if (shared.length > 0) {
    const label = shared[0]!;
    return { v: 1, reason: `Same industry: ${label}` };
  }
  return { v: 0, reason: null };
}

/**
 * Intent scoring is the HEART of matching. Complementary intents score high;
 * same intents score low. Examples:
 *   hiring <-> looking_for_clients        → 1.0  (strong fit)
 *   seeking_funding <-> hiring            → 0.3  (weak)
 *   looking_for_clients <-> looking_for_clients → 0.1 (both sellers)
 */
const INTENT_PAIRS: Record<string, Record<string, number>> = {
  hiring: {
    looking_for_clients: 1.0,
    collaboration: 0.8,
    learning: 0.4,
    showcase: 0.5,
    seeking_funding: 0.2,
    hiring: 0.1,
  },
  looking_for_clients: {
    hiring: 1.0,
    collaboration: 0.7,
    seeking_funding: 0.3,
    learning: 0.2,
    showcase: 0.4,
    looking_for_clients: 0.1,
  },
  seeking_funding: {
    hiring: 0.4,
    collaboration: 0.8,
    looking_for_clients: 0.3,
    showcase: 0.5,
    learning: 0.2,
    seeking_funding: 0.3,
  },
  collaboration: {
    collaboration: 0.9,
    hiring: 0.8,
    looking_for_clients: 0.7,
    seeking_funding: 0.8,
    learning: 0.5,
    showcase: 0.4,
  },
  learning: {
    showcase: 0.7,
    collaboration: 0.5,
    learning: 0.4,
    hiring: 0.4,
    looking_for_clients: 0.2,
    seeking_funding: 0.2,
  },
  showcase: {
    learning: 0.7,
    collaboration: 0.4,
    hiring: 0.5,
    looking_for_clients: 0.4,
    seeking_funding: 0.5,
    showcase: 0.2,
  },
};

function intentReasonText(myIntent: string, theirIntent: string): string {
  const pretty = (k: string) =>
    k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return `You: ${pretty(myIntent)} · Them: ${pretty(theirIntent)}`;
}

function intentScore(me: UserSignals, them: UserSignals): {
  v: number;
  reason: string | null;
} {
  if (!me.intent || !them.intent) return { v: 0, reason: null };
  const v = INTENT_PAIRS[me.intent]?.[them.intent] ?? 0;
  if (v < 0.4) return { v, reason: null };
  return { v, reason: intentReasonText(me.intent, them.intent) };
}

function behaviorScore(me: UserSignals, them: UserSignals): {
  v: number;
  reason: string | null;
} {
  // Overlap of who you both like + who you both follow
  const likeOverlap = overlap(me.liked_authors, them.liked_authors);
  const followOverlap = overlap(me.follows, them.follows);
  const total = likeOverlap + followOverlap;
  if (total === 0) return { v: 0, reason: null };
  // Normalize softly: each overlap counts up to 5, saturates at 10 → 1.0
  const v = Math.min(1, total / 10);
  const reason =
    total >= 3 ? `Similar taste (${total} shared interactions)` : null;
  return { v, reason };
}

function networkScore(me: UserSignals, them: UserSignals): {
  v: number;
  reason: string | null;
} {
  const mutual = overlap(me.connections, them.connections);
  if (mutual === 0) return { v: 0, reason: null };
  const v = Math.min(1, mutual / 3); // 3 mutuals = full trust boost
  return {
    v,
    reason: mutual === 1 ? "1 mutual connection" : `${mutual} mutual connections`,
  };
}

// ---------- UserContext helper (for AI prompts) ----------

/**
 * Build the LLM-friendly view of a user from their signals + profile row.
 * Shared between getTopMatches (AI reasons) and the intro-message server
 * action, so both sides see the same view of the user.
 */
export function toUserContext(
  profile: {
    username: string;
    full_name?: string | null;
    bio?: string | null;
  },
  signals: UserSignals,
  prefsExtra?: { looking_for?: string[] | null } | null,
): UserContext {
  return {
    username: profile.username,
    full_name: profile.full_name ?? null,
    bio: profile.bio ?? null,
    industries: [...signals.industries],
    skills: [...signals.skills],
    tools: [...signals.tools],
    intent: signals.intent,
    looking_for:
      prefsExtra?.looking_for ?? [...signals.looking_for],
  };
}

// ---------- main entry point ----------

export type MatchOptions = {
  limit?: number;      // default 10
  minScore?: number;   // default 0 — return everyone above this
  /**
   * When true (default), candidates scoring >= 60 get an Anthropic-generated
   * natural-language reason attached. Set false on hot paths that don't
   * need it (e.g. pair lookup for a hidden badge).
   */
  aiReasons?: boolean;
  /** Max number of AI reason calls to spend on this query. Default 6. */
  aiReasonBudget?: number;
};

export async function getTopMatches(
  supabase: SupabaseClient,
  userId: string,
  opts: MatchOptions = {},
): Promise<MatchCandidate[]> {
  const limit = opts.limit ?? 10;
  const minScore = opts.minScore ?? 0;
  const aiReasons = opts.aiReasons ?? true;
  const aiBudget = opts.aiReasonBudget ?? 6;

  const me = await buildUserSignals(supabase, userId);

  // Grab the caller's own profile row — we need username/full_name/bio for
  // the AI prompt. Keep it optional: if the lookup fails we just skip AI.
  const { data: myProfile } = await supabase
    .from("profiles")
    .select("username, full_name, bio")
    .eq("id", userId)
    .maybeSingle();
  const meProfile = myProfile as
    | { username: string; full_name: string | null; bio: string | null }
    | null;

  // Candidate pool: every profile except me.
  // TODO: when user count grows, restrict to recently-active users or a
  // coarse pre-filter (same industry OR overlapping skills).
  const { data: profiles } = await supabase
    .from("profiles")
    .select("id, username, full_name, avatar_url, bio")
    .neq("id", userId)
    .limit(500);

  type ProfileRow = {
    id: string;
    username: string;
    full_name: string | null;
    avatar_url: string | null;
    bio: string | null;
  };
  const profileRows = (profiles as ProfileRow[] | null) ?? [];

  // Existing connection state, so we can reflect it in the UI
  const { data: connRows } = await supabase
    .from("connections")
    .select("requester_id, addressee_id, status")
    .or(`requester_id.eq.${userId},addressee_id.eq.${userId}`);

  const connStatus = new Map<string, MatchCandidate["connection_status"]>();
  for (const c of (connRows ??
    []) as {
    requester_id: string;
    addressee_id: string;
    status: "pending" | "accepted" | "declined";
  }[]) {
    const peer = c.requester_id === userId ? c.addressee_id : c.requester_id;
    if (c.status === "accepted") connStatus.set(peer, "connected");
    else if (c.status === "pending") {
      connStatus.set(
        peer,
        c.requester_id === userId ? "pending_outgoing" : "pending_incoming",
      );
    }
  }

  // Score every candidate in parallel; remember each candidate's signals so
  // we can rebuild UserContext for the AI pass without refetching.
  type Scored = MatchCandidate & { _them?: UserSignals };
  const scored: Scored[] = [];
  for (const p of profileRows) {
    const them = await buildUserSignals(supabase, p.id);

    const sk = skillScore(me, them);
    const ind = industryScore(me, them);
    const intn = intentScore(me, them);
    const beh = behaviorScore(me, them);
    const net = networkScore(me, them);

    const raw =
      sk.v * 25 + ind.v * 15 + intn.v * 30 + beh.v * 20 + net.v * 10;
    const score = Math.round(raw);

    if (score < minScore) continue;

    const reasons = [sk.reason, ind.reason, intn.reason, beh.reason, net.reason]
      .filter((r): r is string => !!r)
      .slice(0, 3);

    // Fallback reason when score is low-but-visible so card isn't empty
    if (reasons.length === 0) {
      reasons.push("Nearby in the Trendly network");
    }

    scored.push({
      user_id: p.id,
      username: p.username,
      full_name: p.full_name,
      avatar_url: p.avatar_url,
      bio: p.bio,
      score,
      label: labelFor(score),
      reasons,
      ai_reason: null,
      connection_status: connStatus.get(p.id) ?? "none",
      breakdown: {
        skill: Math.round(sk.v * 25),
        industry: Math.round(ind.v * 15),
        intent: Math.round(intn.v * 30),
        behavior: Math.round(beh.v * 20),
        network: Math.round(net.v * 10),
      },
      _them: them,
    });
  }

  // Rank by score desc; tiebreak by username for stability
  scored.sort((a, b) =>
    b.score !== a.score ? b.score - a.score : a.username.localeCompare(b.username),
  );

  const top = scored.slice(0, limit);

  // ----- AI enrichment pass -----
  // For the visible top-N, upgrade the heuristic reasons[0] with a natural-
  // language reason from Claude. Bounded by aiReasonBudget so a long list
  // doesn't fan out uncontrollably.
  if (aiReasons && meProfile) {
    const meCtx = toUserContext(meProfile, me);
    const aiTargets = top
      .filter((c) => c.score >= 60)
      .slice(0, Math.max(0, aiBudget));

    await Promise.all(
      aiTargets.map(async (c) => {
        if (!c._them) return;
        const themCtx = toUserContext(
          { username: c.username, full_name: c.full_name, bio: c.bio },
          c._them,
        );
        try {
          const reason = await generateMatchReason(meCtx, themCtx, {
            score: c.score,
            ...c.breakdown,
          });
          if (reason) {
            c.ai_reason = reason;
            // Surface AI reason first in the list while keeping heuristic
            // reasons as supporting bullets.
            c.reasons = [reason, ...c.reasons.filter((r) => r !== reason)].slice(
              0,
              3,
            );
          }
        } catch {
          // silent fallback — heuristic reasons already in place
        }
      }),
    );
  }

  // Strip internal-only fields before returning to callers
  return top.map(({ _them: _omit, ...rest }) => {
    void _omit;
    return rest;
  });
}

/**
 * Compute match between caller and a single target user — used on profile
 * pages to show the "You're a X% match" badge. We spend ONE AI reason here
 * (not the full budget) since only one candidate is visible.
 */
export async function getPairMatch(
  supabase: SupabaseClient,
  meId: string,
  theirId: string,
): Promise<MatchCandidate | null> {
  if (meId === theirId) return null;
  const matches = await getTopMatches(supabase, meId, {
    limit: 500,
    aiReasons: false,
  });
  const found = matches.find((m) => m.user_id === theirId);
  if (!found) return null;

  // If the badge is going to render, spend one AI call to make the copy
  // feel human. Only when the score clears the "worth-showing" threshold.
  if (found.score >= 60) {
    try {
      const [myProfileRes, themSignals, themProfileRes] = await Promise.all([
        supabase
          .from("profiles")
          .select("username, full_name, bio")
          .eq("id", meId)
          .maybeSingle(),
        buildUserSignals(supabase, theirId),
        supabase
          .from("profiles")
          .select("username, full_name, bio")
          .eq("id", theirId)
          .maybeSingle(),
      ]);
      const myProfile = myProfileRes.data as
        | { username: string; full_name: string | null; bio: string | null }
        | null;
      const themProfile = themProfileRes.data as
        | { username: string; full_name: string | null; bio: string | null }
        | null;
      if (myProfile && themProfile) {
        const mySignals = await buildUserSignals(supabase, meId);
        const reason = await generateMatchReason(
          toUserContext(myProfile, mySignals),
          toUserContext(themProfile, themSignals),
          { score: found.score, ...found.breakdown },
        );
        if (reason) {
          found.ai_reason = reason;
          found.reasons = [reason, ...found.reasons.filter((r) => r !== reason)].slice(
            0,
            3,
          );
        }
      }
    } catch {
      // swallow — heuristic reasons remain
    }
  }

  return found;
}
