import { Product } from '@/types/database';

export const MOCK_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Ayurvedic Hair Oil',
        slug: 'ayurvedic-hair-oil',
        description: 'HealMitra Ayurvedic Hair Oil is enriched with powerful herbs that nourish the scalp, strengthen roots, and promote healthy hair growth.',
        short_description: 'Enriched with powerful herbs that nourish the scalp, strengthen roots, and promote healthy hair growth.',
        category: 'Hair Care',
        price: 449,
        mrp: 599,
        stock_quantity: 50,
        sku: 'HM-HAIR-001',
        weight: '100ml',
        images: [],
        ingredients: ['Coconut Oil', 'Sesame Oil', 'Bhringraj', 'Brahmi', 'Amla', 'Neem', 'Hibiscus'],
        benefits: ['Reduces hair fall', 'Strengthens hair roots', 'Improves scalp health', 'Enhances natural shine'],
        usage_instructions: '1. Apply required quantity to scalp and hair\n2. Massage gently\n3. Leave for 1–2 hours or overnight\n4. Wash with mild shampoo\n5. Use 2–3 times a week',
        is_active: true,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        id: '2',
        name: 'Manjistha Soap',
        slug: 'manjistha-soap',
        description: 'Manjistha Soap is known for its skin-purifying properties and helps promote clear, healthy skin.',
        short_description: 'Known for its skin-purifying properties and helps promote clear, healthy skin.',
        category: 'Skin Care',
        price: 149,
        mrp: 199,
        stock_quantity: 100,
        sku: 'HM-SOAP-001',
        weight: '80g',
        images: [],
        benefits: ['Helps reduce acne and blemishes', 'Supports natural skin glow', 'Gentle cleansing', 'Suitable for regular use'],
        usage_instructions: '1. Apply on wet skin\n2. Massage gently\n3. Rinse thoroughly',
        is_active: true,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        id: '3',
        name: 'Chandan Soap',
        slug: 'chandan-soap',
        description: 'Chandan Soap soothes the skin and provides a cooling, refreshing effect while maintaining natural moisture.',
        short_description: 'Soothes the skin and provides a cooling, refreshing effect while maintaining natural moisture.',
        category: 'Skin Care',
        price: 149,
        mrp: 199,
        stock_quantity: 100,
        sku: 'HM-SOAP-002',
        weight: '80g',
        images: [],
        benefits: ['Cooling and calming effect', 'Improves skin texture', 'Helps reduce skin irritation', 'Refreshes the skin'],
        usage_instructions: '1. Apply on wet skin\n2. Massage gently\n3. Rinse thoroughly',
        is_active: true,
        featured: true,
        created_at: new Date().toISOString()
    },
    {
        id: '4',
        name: 'Herbal Face Serum',
        slug: 'herbal-face-serum',
        description: 'A lightweight herbal serum formulated to nourish the skin, enhance glow, and maintain hydration.',
        short_description: 'A lightweight herbal serum formulated to nourish the skin, enhance glow, and maintain hydration.',
        category: 'Skin Care',
        price: 349,
        mrp: 449,
        stock_quantity: 30,
        sku: 'HM-SERUM-001',
        weight: '15ml',
        images: [],
        benefits: ['Improves skin radiance', 'Helps maintain moisture', 'Supports healthy skin tone'],
        usage_instructions: '1. Apply a few drops on clean face\n2. Massage gently\n3. Use daily for best results',
        is_active: true,
        featured: true,
        created_at: new Date().toISOString()
    }
];
