// Curated seed recipes — 12 variety-pack covering breakfast/lunch/dinner.
// US units, realistic macros. Inserted as user-owned when the user clicks
// "load starter library" on an empty /recipes page.

import type { Ingredient, Step } from "@/lib/types/database";

export interface SeedRecipe {
  name: string;
  photo_url: string | null;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  time_min: number;
  tags: string[];
  ingredients_json: Ingredient[];
  steps_json: Step[];
}

export const SEED_RECIPES: SeedRecipe[] = [
  {
    name: "Greek yogurt parfait with walnuts",
    photo_url: null,
    kcal: 380,
    protein: 28,
    carbs: 38,
    fat: 14,
    time_min: 5,
    tags: ["breakfast", "high-protein", "vegetarian"],
    ingredients_json: [
      { name: "plain greek yogurt", qty: 1, unit: "cup", aisle: "dairy" },
      { name: "blueberries", qty: 0.5, unit: "cup", aisle: "produce" },
      { name: "walnuts", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "honey", qty: 1, unit: "tsp", aisle: "pantry" },
      { name: "rolled oats", qty: 2, unit: "tbsp", aisle: "pantry" },
    ],
    steps_json: [
      { text: "Spoon yogurt into a bowl or glass." },
      { text: "Top with blueberries, walnuts, oats, and a drizzle of honey." },
    ],
  },
  {
    name: "Veggie scramble with toast",
    photo_url: null,
    kcal: 460,
    protein: 26,
    carbs: 36,
    fat: 22,
    time_min: 12,
    tags: ["breakfast", "vegetarian"],
    ingredients_json: [
      { name: "eggs", qty: 3, unit: "each", aisle: "dairy" },
      { name: "spinach", qty: 1, unit: "cup", aisle: "produce" },
      { name: "cherry tomatoes", qty: 0.5, unit: "cup", aisle: "produce" },
      { name: "feta cheese", qty: 2, unit: "tbsp", aisle: "dairy", optional: true },
      { name: "whole grain bread", qty: 2, unit: "each", aisle: "bakery" },
      { name: "olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { name: "salt", qty: 1, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Heat olive oil in a non-stick pan over medium heat." },
      { text: "Add tomatoes, cook 1 minute, then add spinach until wilted." },
      { text: "Whisk eggs with a pinch of salt; pour over the veg." },
      { text: "Stir gently until just set, about 90 seconds." },
      { text: "Crumble feta on top. Toast bread and serve alongside." },
    ],
  },
  {
    name: "Overnight oats with peanut butter",
    photo_url: null,
    kcal: 420,
    protein: 18,
    carbs: 56,
    fat: 14,
    time_min: 5,
    tags: ["breakfast", "make-ahead", "vegetarian"],
    ingredients_json: [
      { name: "rolled oats", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "milk", qty: 0.75, unit: "cup", aisle: "dairy" },
      { name: "peanut butter", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "chia seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "banana", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "honey", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
    steps_json: [
      { text: "Combine oats, milk, peanut butter, chia, and honey in a jar." },
      { text: "Stir well, cover, and refrigerate overnight." },
      { text: "In the morning, top with sliced banana." },
    ],
  },
  {
    name: "Chicken caesar lunch bowl",
    photo_url: null,
    kcal: 520,
    protein: 42,
    carbs: 28,
    fat: 26,
    time_min: 20,
    tags: ["lunch", "high-protein"],
    ingredients_json: [
      { name: "chicken breast", qty: 6, unit: "oz", aisle: "protein" },
      { name: "romaine lettuce", qty: 3, unit: "cup", aisle: "produce" },
      { name: "parmesan cheese", qty: 2, unit: "tbsp", aisle: "dairy" },
      { name: "croutons", qty: 0.25, unit: "cup", aisle: "bakery" },
      { name: "caesar dressing", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { name: "salt", qty: 0.5, unit: "tsp", aisle: "spices" },
      { name: "black pepper", qty: 0.25, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Season chicken with salt and pepper." },
      { text: "Sear in olive oil over medium-high heat, 4 minutes per side, until 165 °F.", timer_sec: 480 },
      { text: "Rest chicken 3 minutes, then slice." },
      { text: "Toss romaine with dressing and parmesan in a bowl." },
      { text: "Top with sliced chicken and croutons." },
    ],
  },
  {
    name: "Turkey hummus wrap",
    photo_url: null,
    kcal: 480,
    protein: 30,
    carbs: 48,
    fat: 18,
    time_min: 8,
    tags: ["lunch", "quick", "high-protein"],
    ingredients_json: [
      { name: "whole wheat tortilla", qty: 1, unit: "each", aisle: "bakery" },
      { name: "deli turkey", qty: 4, unit: "oz", aisle: "protein" },
      { name: "hummus", qty: 3, unit: "tbsp", aisle: "pantry" },
      { name: "spinach", qty: 1, unit: "cup", aisle: "produce" },
      { name: "cucumber", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "red bell pepper", qty: 0.5, unit: "each", aisle: "produce" },
    ],
    steps_json: [
      { text: "Spread hummus across the tortilla." },
      { text: "Layer turkey, spinach, sliced cucumber, and pepper strips." },
      { text: "Roll tightly, slice in half, serve." },
    ],
  },
  {
    name: "Quinoa power bowl",
    photo_url: null,
    kcal: 540,
    protein: 22,
    carbs: 64,
    fat: 22,
    time_min: 25,
    tags: ["lunch", "vegetarian", "make-ahead"],
    ingredients_json: [
      { name: "quinoa", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "chickpeas", qty: 1, unit: "can", aisle: "pantry" },
      { name: "kale", qty: 2, unit: "cup", aisle: "produce" },
      { name: "avocado", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "cherry tomatoes", qty: 0.5, unit: "cup", aisle: "produce" },
      { name: "tahini", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "lemon", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "olive oil", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
    steps_json: [
      { text: "Rinse and cook quinoa in 1 cup water for 15 minutes.", timer_sec: 900 },
      { text: "Drain and rinse chickpeas, then toss with olive oil and roast at 400 °F for 15 minutes.", timer_sec: 900 },
      { text: "Massage kale with a pinch of salt until tender." },
      { text: "Whisk tahini with lemon juice and 1 tbsp water for dressing." },
      { text: "Build the bowl: quinoa, kale, chickpeas, tomatoes, avocado. Drizzle dressing." },
    ],
  },
  {
    name: "Sheet pan salmon and broccoli",
    photo_url: null,
    kcal: 520,
    protein: 38,
    carbs: 22,
    fat: 30,
    time_min: 25,
    tags: ["dinner", "one-pan", "high-protein"],
    ingredients_json: [
      { name: "salmon fillet", qty: 6, unit: "oz", aisle: "protein" },
      { name: "broccoli florets", qty: 2, unit: "cup", aisle: "produce" },
      { name: "olive oil", qty: 1.5, unit: "tbsp", aisle: "pantry" },
      { name: "lemon", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "garlic", qty: 2, unit: "each", aisle: "produce" },
      { name: "salt", qty: 0.75, unit: "tsp", aisle: "spices" },
      { name: "black pepper", qty: 0.25, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Heat oven to 425 °F." },
      { text: "Toss broccoli with 1 tbsp olive oil, minced garlic, salt, and pepper. Spread on a sheet pan." },
      { text: "Place salmon on the same pan, brush with remaining oil, season, top with lemon slices." },
      { text: "Roast 14 minutes until salmon flakes.", timer_sec: 840 },
      { text: "Squeeze remaining lemon over the plate before serving." },
    ],
  },
  {
    name: "Chicken stir-fry with brown rice",
    photo_url: null,
    kcal: 560,
    protein: 40,
    carbs: 58,
    fat: 18,
    time_min: 25,
    tags: ["dinner", "high-protein"],
    ingredients_json: [
      { name: "chicken breast", qty: 6, unit: "oz", aisle: "protein" },
      { name: "brown rice", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "snap peas", qty: 1, unit: "cup", aisle: "produce" },
      { name: "red bell pepper", qty: 1, unit: "each", aisle: "produce" },
      { name: "garlic", qty: 2, unit: "each", aisle: "produce" },
      { name: "ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { name: "soy sauce", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "sesame oil", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "honey", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
    steps_json: [
      { text: "Cook brown rice per package, about 25 minutes.", timer_sec: 1500 },
      { text: "Slice chicken into bite-sized strips. Toss with 1 tbsp soy sauce." },
      { text: "Heat sesame oil in a wok or large pan over high heat." },
      { text: "Sear chicken until golden, 3 minutes. Remove." },
      { text: "Add peppers, snap peas, garlic, and ginger. Stir-fry 3 minutes." },
      { text: "Return chicken, add remaining soy sauce and honey. Toss 1 minute." },
      { text: "Serve over rice." },
    ],
  },
  {
    name: "Black bean tacos",
    photo_url: null,
    kcal: 480,
    protein: 22,
    carbs: 62,
    fat: 16,
    time_min: 15,
    tags: ["dinner", "vegetarian", "quick"],
    ingredients_json: [
      { name: "black beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "corn tortillas", qty: 4, unit: "each", aisle: "bakery" },
      { name: "avocado", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "red onion", qty: 0.25, unit: "each", aisle: "produce" },
      { name: "cilantro", qty: 0.25, unit: "cup", aisle: "produce" },
      { name: "lime", qty: 1, unit: "each", aisle: "produce" },
      { name: "cumin", qty: 1, unit: "tsp", aisle: "spices" },
      { name: "paprika", qty: 0.5, unit: "tsp", aisle: "spices" },
      { name: "salt", qty: 0.5, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Drain beans, then warm in a pan with cumin, paprika, salt, and 2 tbsp water." },
      { text: "Mash about half the beans for texture." },
      { text: "Char tortillas 30 seconds per side over the burner.", timer_sec: 60 },
      { text: "Top tortillas with beans, sliced avocado, red onion, cilantro." },
      { text: "Squeeze lime over the top." },
    ],
  },
  {
    name: "Spaghetti with garlic shrimp",
    photo_url: null,
    kcal: 580,
    protein: 32,
    carbs: 62,
    fat: 22,
    time_min: 20,
    tags: ["dinner", "high-protein"],
    ingredients_json: [
      { name: "spaghetti", qty: 3, unit: "oz", aisle: "pantry" },
      { name: "shrimp", qty: 6, unit: "oz", aisle: "protein" },
      { name: "garlic", qty: 4, unit: "each", aisle: "produce" },
      { name: "olive oil", qty: 2, unit: "tbsp", aisle: "pantry" },
      { name: "red pepper flakes", qty: 0.5, unit: "tsp", aisle: "spices" },
      { name: "lemon", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "parsley", qty: 2, unit: "tbsp", aisle: "produce" },
      { name: "salt", qty: 0.75, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Boil salted water. Cook spaghetti per package.", timer_sec: 540 },
      { text: "Reserve 1/2 cup pasta water before draining." },
      { text: "Heat olive oil in a pan, add sliced garlic and red pepper flakes." },
      { text: "When garlic is golden, add shrimp. Cook 2 minutes per side until pink." },
      { text: "Toss in pasta with a splash of pasta water. Finish with lemon juice and parsley." },
    ],
  },
  {
    name: "Turkey chili",
    photo_url: null,
    kcal: 460,
    protein: 38,
    carbs: 38,
    fat: 16,
    time_min: 40,
    tags: ["dinner", "make-ahead", "high-protein"],
    ingredients_json: [
      { name: "ground turkey", qty: 1, unit: "lb", aisle: "protein" },
      { name: "kidney beans", qty: 1, unit: "can", aisle: "pantry" },
      { name: "diced tomatoes", qty: 1, unit: "can", aisle: "pantry" },
      { name: "onion", qty: 1, unit: "each", aisle: "produce" },
      { name: "garlic", qty: 3, unit: "each", aisle: "produce" },
      { name: "chili powder", qty: 2, unit: "tbsp", aisle: "spices" },
      { name: "cumin", qty: 1, unit: "tbsp", aisle: "spices" },
      { name: "olive oil", qty: 1, unit: "tbsp", aisle: "pantry" },
      { name: "salt", qty: 1, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Heat olive oil in a pot. Sweat diced onion and garlic for 4 minutes." },
      { text: "Add turkey, breaking up, until browned, about 7 minutes.", timer_sec: 420 },
      { text: "Stir in chili powder, cumin, and salt." },
      { text: "Add tomatoes (with juice) and drained beans." },
      { text: "Simmer uncovered 25 minutes, stirring occasionally.", timer_sec: 1500 },
      { text: "Taste, adjust salt. Serves 4 — keeps 4 days in fridge." },
    ],
  },
  {
    name: "Mediterranean chicken bowl",
    photo_url: null,
    kcal: 600,
    protein: 44,
    carbs: 48,
    fat: 24,
    time_min: 30,
    tags: ["dinner", "high-protein", "make-ahead"],
    ingredients_json: [
      { name: "chicken thigh", qty: 6, unit: "oz", aisle: "protein" },
      { name: "couscous", qty: 0.5, unit: "cup", aisle: "pantry" },
      { name: "cherry tomatoes", qty: 0.75, unit: "cup", aisle: "produce" },
      { name: "cucumber", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "kalamata olives", qty: 8, unit: "each", aisle: "pantry" },
      { name: "feta cheese", qty: 2, unit: "tbsp", aisle: "dairy" },
      { name: "olive oil", qty: 1.5, unit: "tbsp", aisle: "pantry" },
      { name: "lemon", qty: 0.5, unit: "each", aisle: "produce" },
      { name: "oregano", qty: 1, unit: "tsp", aisle: "spices" },
      { name: "garlic", qty: 2, unit: "each", aisle: "produce" },
      { name: "salt", qty: 0.75, unit: "tsp", aisle: "spices" },
    ],
    steps_json: [
      { text: "Marinate chicken in 1 tbsp olive oil, garlic, oregano, salt, and lemon juice for 10 min." },
      { text: "Cook couscous per package, fluff with a fork." },
      { text: "Sear chicken in a hot pan 5 minutes per side until 165 °F.", timer_sec: 600 },
      { text: "Slice and arrange over couscous with cucumber, tomatoes, olives, and feta." },
      { text: "Drizzle remaining olive oil and a squeeze of lemon." },
    ],
  },
];
