// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blogs']['schema']['_output']
export declare const blogs: Blog[]

export type Service = Collections['services']['schema']['_output']
export declare const services: Service[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]

export type CaseStudy = Collections['caseStudies']['schema']['_output']
export declare const caseStudies: CaseStudy[]
