export const PROPERTY_TYPES = [
  { value: "apartment", label: "Apartment" },
  { value: "house", label: "House" },
  { value: "room", label: "Room" },
  { value: "condo", label: "Condo" },
  { value: "townhouse", label: "Townhouse" },
] as const;

export const AVAILABILITY_STATUSES = [
  { value: "available", label: "Available", color: "bg-green-100 text-green-800" },
  { value: "reserved", label: "Reserved", color: "bg-yellow-100 text-yellow-800" },
  { value: "occupied", label: "Occupied", color: "bg-red-100 text-red-800" },
] as const;

export const BEDROOM_OPTIONS = [
  { value: 0, label: "Studio" },
  { value: 1, label: "1 Bedroom" },
  { value: 2, label: "2 Bedrooms" },
  { value: 3, label: "3 Bedrooms" },
  { value: 4, label: "4+ Bedrooms" },
] as const;

export const PRICE_RANGES = [
  { min: 0, max: 5000, label: "Under P5,000" },
  { min: 5000, max: 10000, label: "P5,000 - P10,000" },
  { min: 10000, max: 20000, label: "P10,000 - P20,000" },
  { min: 20000, max: 50000, label: "P20,000 - P50,000" },
  { min: 50000, max: Infinity, label: "P50,000+" },
] as const;

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "price_asc", label: "Price: Low to High" },
  { value: "price_desc", label: "Price: High to Low" },
] as const;

// Baguio City barangays (129 — source: PSA PSGC)
export const BARANGAYS = [
  "A. Bonifacio-Caguioa-Rimando",
  "Abanao-Zandueta-Kayong-Chugum-Otek",
  "Alfonso Tabora",
  "Ambiong",
  "Andres Bonifacio",
  "Apugan-Loakan",
  "Asin Road",
  "Atok Trail",
  "Aurora Hill Proper",
  "Aurora Hill, North Central",
  "Aurora Hill, South Central",
  "Bagong Lipunan",
  "Bakakeng Central",
  "Bakakeng North",
  "Bal-Marcoville",
  "Balsigan",
  "Bayan Park East",
  "Bayan Park Village",
  "Bayan Park West",
  "BGH Compound",
  "Brookside",
  "Brookspoint",
  "Cabinet Hill-Teacher's Camp",
  "Camdas Subdivision",
  "Camp 7",
  "Camp 8",
  "Camp Allen",
  "Campo Filipino",
  "City Camp Central",
  "City Camp Proper",
  "Country Club Village",
  "Cresencia Village",
  "Dagsian, Lower",
  "Dagsian, Upper",
  "Dizon Subdivision",
  "Dominican Hill-Mirador",
  "Dontogan",
  "DPS Area",
  "Engineers' Hill",
  "Fairview Village",
  "Ferdinand",
  "Fort del Pilar",
  "Gabriela Silang",
  "General Emilio F. Aguinaldo",
  "General Luna, Lower",
  "General Luna, Upper",
  "Gibraltar",
  "Greenwater Village",
  "Guisad Central",
  "Guisad Sorong",
  "Happy Hollow",
  "Happy Homes",
  "Harrison-Claudio Carantes",
  "Hillside",
  "Holy Ghost Extension",
  "Holy Ghost Proper",
  "Honeymoon",
  "Imelda R. Marcos",
  "Imelda Village",
  "Irisan",
  "Kabayanihan",
  "Kagitingan",
  "Kayang Extension",
  "Kayang-Hilltop",
  "Kias",
  "Legarda-Burnham-Kisad",
  "Liwanag-Loakan",
  "Loakan Proper",
  "Lopez Jaena",
  "Lourdes Subdivision Extension",
  "Lourdes Subdivision, Lower",
  "Lourdes Subdivision, Proper",
  "Lualhati",
  "Lucnab",
  "Magsaysay Private Road",
  "Magsaysay, Lower",
  "Magsaysay, Upper",
  "Malcolm Square-Perfecto",
  "Manuel A. Roxas",
  "Market Subdivision, Upper",
  "Middle Quezon Hill Subdivision",
  "Military Cut-off",
  "Mines View Park",
  "Modern Site, East",
  "Modern Site, West",
  "MRR-Queen Of Peace",
  "New Lucban",
  "Outlook Drive",
  "Pacdal",
  "Padre Burgos",
  "Padre Zamora",
  "Palma-Urbano",
  "Phil-Am",
  "Pinget",
  "Pinsao Pilot Project",
  "Pinsao Proper",
  "Poliwes",
  "Pucsusan",
  "Quezon Hill Proper",
  "Quezon Hill, Upper",
  "Quirino Hill, East",
  "Quirino Hill, Lower",
  "Quirino Hill, Middle",
  "Quirino Hill, West",
  "Quirino-Magsaysay, Upper",
  "Rizal Monument Area",
  "Rock Quarry, Lower",
  "Rock Quarry, Middle",
  "Rock Quarry, Upper",
  "Saint Joseph Village",
  "Salud Mitra",
  "San Antonio Village",
  "San Luis Village",
  "San Roque Village",
  "San Vicente",
  "Sanitary Camp, North",
  "Sanitary Camp, South",
  "Santa Escolastica",
  "Santo Rosario",
  "Santo Tomas Proper",
  "Santo Tomas School Area",
  "Scout Barrio",
  "Session Road Area",
  "Slaughter House Area",
  "SLU-SVP Housing Village",
  "South Drive",
  "Teodora Alonzo",
  "Trancoville",
  "Victoria Village",
] as const;

// Default map center: Baguio City
export const BAGUIO_CENTER = {
  lat: 16.4023,
  lng: 120.5960,
} as const;

export const DEFAULT_ZOOM = 14;
