-- Partial unique index on auto-generated recipes — closes the cross-request
-- race in upsertAutoGeneratedRecipe.
--
-- Background: that helper does SELECT-then-INSERT to dedupe recipes by
-- (owner_id, name, kcal, protein) with the "auto-generated" tag. Two
-- concurrent save calls (the most common cause: user impatiently
-- clicking Generate twice during a slow save) can both miss the SELECT
-- and both INSERT, producing duplicate rows. The 60 dupes we already
-- cleaned up on prod (`baked turkey pasta` ×13, `chicken salad wraps`
-- ×19, etc) had exactly this pattern — bursts of inserts within a few
-- hundred ms of each other.
--
-- A DB-level partial unique index lets the second INSERT fail with
-- 23505 (unique_violation), at which point the application catches
-- and re-selects the winning row's id. The "partial" bit is
-- important: user-created and seed recipes can legitimately share
-- names ("Mom's chili" from two different households should be two
-- rows), so the constraint only applies when the tags array contains
-- 'auto-generated'.

begin;

-- ────────────────────────────────────────────────────────────────────
-- Step 1: defensive dedup of any existing auto-generated duplicates.
-- ────────────────────────────────────────────────────────────────────
-- Production was cleaned up by an ad-hoc dedup pass earlier in May
-- 2026, but new self-hosters and family-allowlist users may still
-- have dupes in their projects. CREATE UNIQUE INDEX fails if dupes
-- exist, so we proactively clean them as part of the migration
-- using the same canonical-selection logic (most-referenced wins,
-- tiebreak completeness then age).

with norm as (
  select id, owner_id, name, kcal, protein, created_at,
    jsonb_array_length(coalesce(ingredients_json::jsonb, '[]'::jsonb)) as ing_count
  from recipes
  where 'auto-generated' = any(tags)
    and owner_id is not null
),
ref_counts as (
  select n.*,
    coalesce((select count(*) from meal_plan_entries where recipe_id = n.id), 0)
    + coalesce((select count(*) from meal_logs where recipe_id = n.id), 0)
    + coalesce((select count(*) from saved_recipes where recipe_id = n.id), 0)
    + coalesce((select count(*) from recipe_ratings where recipe_id = n.id), 0) as ref_count
  from norm n
),
groups as (
  select owner_id, name, kcal, protein
  from norm
  group by owner_id, name, kcal, protein
  having count(*) > 1
),
ranked as (
  select rc.*,
    row_number() over (
      partition by rc.owner_id, rc.name, rc.kcal, rc.protein
      order by rc.ref_count desc, rc.ing_count desc, rc.created_at asc
    ) as rn
  from ref_counts rc
  join groups g
    on g.owner_id = rc.owner_id
    and g.name = rc.name
    and g.kcal = rc.kcal
    and g.protein = rc.protein
),
canonical as (
  select owner_id, name, kcal, protein, id as canonical_id
  from ranked
  where rn = 1
),
dedup_map as (
  select r.id as dup_id, c.canonical_id
  from ranked r
  join canonical c
    on c.owner_id = r.owner_id
    and c.name = r.name
    and c.kcal = r.kcal
    and c.protein = r.protein
  where r.rn > 1
)
-- Materialise into a temp table so the same map drives every FK redirect.
select * into temp _auto_dedup_map from dedup_map;

-- Redirect FK references from dup → canonical.
update meal_plan_entries mpe
   set recipe_id = m.canonical_id
  from _auto_dedup_map m
 where mpe.recipe_id = m.dup_id;

update meal_logs ml
   set recipe_id = m.canonical_id
  from _auto_dedup_map m
 where ml.recipe_id = m.dup_id;

update saved_recipes sr
   set recipe_id = m.canonical_id
  from _auto_dedup_map m
 where sr.recipe_id = m.dup_id
   and not exists (
     select 1 from saved_recipes sr2
      where sr2.user_id = sr.user_id and sr2.recipe_id = m.canonical_id
   );
delete from saved_recipes sr using _auto_dedup_map m where sr.recipe_id = m.dup_id;

update recipe_ratings rr
   set recipe_id = m.canonical_id
  from _auto_dedup_map m
 where rr.recipe_id = m.dup_id
   and not exists (
     select 1 from recipe_ratings rr2
      where rr2.user_id = rr.user_id and rr2.recipe_id = m.canonical_id
   );
delete from recipe_ratings rr using _auto_dedup_map m where rr.recipe_id = m.dup_id;

-- Finally drop the duplicate recipe rows.
delete from recipes r using _auto_dedup_map m where r.id = m.dup_id;

drop table _auto_dedup_map;

-- ────────────────────────────────────────────────────────────────────
-- Step 2: create the partial unique index.
-- ────────────────────────────────────────────────────────────────────
-- IF NOT EXISTS so re-runs are no-ops. Non-concurrent because:
--   (a) recipes is a small table (hundreds of rows per user max),
--   (b) CONCURRENTLY can't run inside the transaction wrapping this
--       migration, and a brief AccessExclusive lock on a tiny table
--       is irrelevant in practice.

create unique index if not exists recipes_auto_generated_unique_idx
  on public.recipes (owner_id, name, kcal, protein)
  where 'auto-generated' = any(tags);

commit;
