-- Add synthetic CSAT (Customer Satisfaction) feature

-- Add CSAT toggle to assistants
ALTER TABLE assistants ADD COLUMN enable_csat BOOLEAN DEFAULT false;

-- Add CSAT fields to call_sessions
ALTER TABLE call_sessions ADD COLUMN csat_score INTEGER CHECK (csat_score >= 1 AND csat_score <= 5);
ALTER TABLE call_sessions ADD COLUMN csat_reasoning TEXT;
ALTER TABLE call_sessions ADD COLUMN csat_evaluated_at TIMESTAMPTZ;

-- Add index for CSAT analytics queries
CREATE INDEX idx_call_sessions_csat ON call_sessions(csat_score) WHERE csat_score IS NOT NULL;

COMMENT ON COLUMN assistants.enable_csat IS 'Enable synthetic CSAT scoring for calls with this assistant';
COMMENT ON COLUMN call_sessions.csat_score IS 'Synthetic CSAT score (1-5) generated by LLM analysis of the call';
COMMENT ON COLUMN call_sessions.csat_reasoning IS 'LLM explanation for the CSAT score';
